---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm_chart.fullname" . }}-config
  labels:
    {{- include "helm_chart.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.seqcoordAppProperties }}
  {{ $path }}: |
{{ $config | indent 4 }}
{{- end -}}