{{- range tuple "a" "b" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm_chart.fullname" $ }}-{{ . }}
  labels:
    {{- include "helm_chart.labels" $ | nindent 4 }}
    rcsb.org/path: {{ . | quote }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm_chart.selectorLabels" $ | nindent 6 }}
      rcsb.org/path: {{ . | quote }}
  strategy:
    type: {{ $.Values.deploymentStrategy.type }}
    {{- if eq $.Values.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ $.Values.deploymentStrategy.maxSurge }}
      maxUnavailable: {{ $.Values.deploymentStrategy.maxUnavailable }}
    {{- end }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm_chart.selectorLabels" $ | nindent 8 }}
        rcsb.org/path: {{ . | quote }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "helm_chart.selectorLabels" $ | nindent 20 }}
                topologyKey: kubernetes.io/hostname
              weight: 1
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecrets }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $.Values.service.containerPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/log4j2.xml
              subPath: log4j2.xml
              name: {{ include "helm_chart.fullname" $ }}-config
            # - mountPath: /elastic/apm/agent
            #   name: elastic-apm-agent
            - mountPath: /var/www/seqcoordAppProperties.app.properties
              subPath: seqcoordAppProperties.{{ . }}.app.properties
              name: {{ include "helm_chart.fullname" $ }}-secret
          env:
            - name: JDK_JAVA_OPTIONS
              value: {{ $.Values.javaOptions }}
      volumes:
        - name: {{ include "helm_chart.fullname" $ }}-config
          configMap:
            name: {{ include "helm_chart.fullname" $ }}-config
        - name: {{ include "helm_chart.fullname" $ }}-secret
          secret:
            secretName: {{ include "helm_chart.fullname" $ }}-secret
          # livenessProbe:
          #   initialDelaySeconds: {{ $.Values.initialLivenessDelaySeconds }}
          #   failureThreshold: {{ $.Values.livenessProbe.failureThreshold }}
          #   periodSeconds: {{ $.Values.livenessProbe.periodSeconds }}
          #   httpGet:
          #     path: {{ $.Values.livenessProbe.http.path }}
          #     port: {{ $.Values.service.containerPort }}
          # readinessProbe:
          #   initialDelaySeconds: {{ $.Values.initialReadinessDelaySeconds }}
          #   failureThreshold: {{ $.Values.readinessProbe.failureThreshold }}
          #   periodSeconds: {{ $.Values.readinessProbe.periodSeconds }}
          #   httpGet:
          #     path: {{ $.Values.readinessProbe.http.path }}
          #     port: {{ $.Values.service.containerPort }}
          # resources:
          #   {{- toYaml $.Values.resources | nindent 12 }}
{{- end }}