---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "helm_chart.fullname" . }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: rcsb-vault
    kind: ClusterSecretStore
  target:
    name: {{ include "helm_chart.fullname" . }}-secret
  data:
    - secretKey: apm_secret_token
      remoteRef:
        key: elastic_monitoring/apm_token
        property: apm_secret_token
    - secretKey: mongodb_pwd
      remoteRef:
        key: mongo_databases/admin_accounts
        property: {{ .Values.seqcoordAppProperties.mongoDwUser }}