# Default values for prerelease.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
revisionHistoryLimit: 3

# vaultSecretStoreName is the name of the ClusterSecretStore resource to pull secret credentials
vaultSecretStoreName: "rcsb-vault"

# Define container liveness and readiness checks
# A Pod is considered "live" when it is able to respond to client requests.
# A Pod is considered "ready" when it has completed initialization and should be one of the backends for a K8s Service resource.
initialLivenessDelaySeconds: 120
livenessProbe:
  http:
    path: /
  failureThreshold: 4
  periodSeconds: 30

initialReadinessDelaySeconds: 120
readinessProbe:
  http:
    path: /api/alive
  failureThreshold: 6
  periodSeconds: 30

image:
  repository: harbor.devops.k8s.rcsb.org/rcsb/rcsb-sequence-coordinates
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "k8s-staging"

imagePullSecrets: "harbor-docker-registry-conf"




deploymentStrategy:
  #https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  #Type is either RollingUpdate or Recreate
  type: "RollingUpdate"
  #For rolling update, what percentage of total pods can be created above desired amount
  maxSurge: 25%
  #For rolling update, what percentage of total pods can be brought down to update
  maxUnavailable: 25%

podSecurityContext:
  fsGroup: 33
  runAsNonRoot: true
  runAsUser: 33
  runAsGroup: 33
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 8
    memory: 96Gi
  requests:
    cpu: 4
    memory: 64Gi
